openapi: 3.0.0
info:
  title: eRock API
  version: 1.0.0
paths:
  /evaluate:
    post:
      summary: Evaluate expression
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                expr:
                  type: string
                  example: "2 + 3 * 4"
                variables:
                  type: object
                  additionalProperties:
                    type: array
                    items:
                      type: number
                  example: {"x": [5.0]}
      responses:
        '200':
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    type: number
                  error:
                    type: string
                    nullable: true
  /health:
    get:
      summary: Health check
      responses:
        '200':
          description: OK
