name: DCO
on:
  pull_request:
    types: [opened, synchronize, reopened, edited]
jobs:
  dco:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
    steps:
      - name: Check DCO sign-offs
        run: |
          set -euo pipefail
          repo="${{ github.repository }}"
          pr="${{ github.event.pull_request.number }}"
          url="https://api.github.com/repos/$repo/pulls/$pr/commits"
          missing=$(curl -fsSL -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" -H "Accept: application/vnd.github+json" "$url" \
            | jq -r '.[] | select(.commit.message | test("(?i)signed-off-by:\\s*.+<.+@.+>") | not) | "\(.sha[0:7])  \(.commit.message | split(\"\\n\")[0])"' )
          if [ -n "$missing" ]; then
            echo "These commits are missing a Signed-off-by line:"
            echo "$missing"
            echo
            echo "Fix locally with:"
            echo "  git commit --amend -s  # then git push --force-with-lease"
            echo "or for multiple commits:"
            echo "  git rebase -i --rebase-merges <base>  # mark as edit, then amend each with -s"
            exit 1
          fi
